name: Arklint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  arklint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: Kaushik13k/ark-lint@main
        with:
          strict: "true"
          diff: "origin/main"